# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Chocolatey Action'
description: 'GitHub Action for Chocolatey, the package manager for Windows'
author: 'crazy-max'
branding:
  color: 'blue'
  icon: 'terminal'

inputs:
  args:
    description: 'Arguments to pass to Chocolatey'
    required: true
  image:
    description: 'Docker image to use'
    default: 'ghcr.io/crazy-max/chocolatey'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
