name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - 'master'
      - 'releases/v*'
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      -
        name: Build image
        uses: docker/bake-action@82490499d2e5613fcead7e128237ef0b0ea210f7 # v7.0.0
        with:
          source: .
          targets: image-local
      -
        name: Choco help
        uses: ./
        with:
          args: -h
          image: chocolatey:local
      -
        name: Choco install InnoSetup
        uses: ./
        with:
          args: install innosetup --no-progress
          image: chocolatey:local

  windows:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      -
        name: Choco help
        uses: ./
        with:
          args: -h
      -
        name: Choco install InnoSetup
        uses: ./
        with:
          args: install innosetup --no-progress
