name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - 'master'
      - 'releases/v*'
  pull_request:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      -
        name: Build image
        uses: docker/bake-action@d3418bd7d0e9324001bca92fa8ba175ea7e6dc9b # v7.3.0
        with:
          source: .
          targets: image-local
      -
        name: Choco help
        uses: ./
        with:
          args: -h
          image: chocolatey:local
      -
        name: Choco install InnoSetup
        uses: ./
        with:
          args: install innosetup --no-progress
          image: chocolatey:local

  windows:
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      -
        name: Choco help
        uses: ./
        with:
          args: -h
      -
        name: Choco install InnoSetup
        uses: ./
        with:
          args: install innosetup --no-progress
