name: image

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

on:
  push:
    branches:
      - 'master'
      - 'releases/v*'
    tags:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:

env:
  DOCKERHUB_SLUG: crazymax/ghaction-chocolatey
  GHCR_SLUG: ghcr.io/crazy-max/chocolatey

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read # same as global permissions
      packages: write # required to push to GHCR
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: |
            ${{ env.DOCKERHUB_SLUG }}
            ${{ env.GHCR_SLUG }}
          tags: |
            type=ref,event=tag
            type=ref,event=pr
            type=edge
          labels: |
            org.opencontainers.image.title=Chocolatey Action
            org.opencontainers.image.description=GitHub Action for Chocolatey, the package manager for Windows
            org.opencontainers.image.vendor=CrazyMax
            com.github.actions.name=Chocolatey Action
            com.github.actions.description=GitHub Action for Chocolatey, the package manager for Windows
            com.github.actions.icon=terminal
            com.github.actions.color=blue
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0
      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build
        uses: docker/bake-action@6614cfa25eff9a0b2b2697efb0b6159e7680d584 # v7.2.0
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.meta.outputs.bake-file }}
          targets: image
          push: ${{ github.event_name != 'pull_request' }}
